config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users, only: [:new, :create]
  resources :links, only: [:index, :create, :edit, :update, :destroy]

  namespace :api do
    namespace :v1 do
      resources :links, defaults: { format: :json } do
        member do
          patch 'toggle_read'
        end
      end
    end
  end
end

app/models/link.rb
class Link < ActiveRecord::Base
  belongs_to :user
  validates :url, presence: true, :url => true
  validates :title, presence: true

  def toggle
    if self.read
      self.update(read: false)
    else
      self.update(read: true)
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :links

  validates :email, uniqueness: true
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ApplicationController
  respond_to :json
end

app/controllers/api/v1/links_controller.rb
class Api::V1::LinksController < Api::V1::BaseController
  # def update
  #   @link = Link.find(params[:id])
  #   respond_with @link.update(link_params)
  # end

  def toggle_read
    @link = Link.find(params[:id])
    respond_with @link.toggle
  end

  private

  def link_params
    params.permit(:url, :title, :read)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
  helper_method :current_user, :authenticate!

  def current_user
    @user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authenticate!
    redirect_to '/' unless current_user
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :authenticate!

  def index
    @links = current_user.links
  end

  def create
    @link = current_user.links.new(link_params)
    if @link.save
      flash.now[:notice] = "Successfully added #{@link.title}"
      redirect_to links_path
    else
      flash[:error] = @link.errors.full_messages.join(' ')
      redirect_to links_path
    end
  end

  def edit
    @link = Link.find(params[:id])
  end

  def update
    @link = Link.find(params[:id])
    if @link.update(link_params)
      flash.now[:notice] = "Successfully updated #{@link.title}"
      redirect_to links_path
    else
      flash[:error] = @link.errors.full_messages.join(' ')
      render :edit
    end
  end

  def destroy
    @link = Link.find(params[:id]).destroy
    redirect_to links_path
  end

  private

  def link_params
    params.require(:link).permit(:url, :title)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to links_path
    else
      flash.now[:error] = "Invalid Credentials"
      render :new
    end
  end

  def destroy
    session.clear
    redirect_to '/'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Logged in as #{@user.email}"
      redirect_to links_path
    else
      flash.now[:error] = @user.errors.full_messages.join(' ')
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Thoughtbox</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="#">ThoughtBox</a>
      <ul class="nav navbar-nav navbar-right">
      <% if current_user %>
        <li><%= button_to 'Logout', logout_path, method: 'delete', class: 'btn btn-default navbar-btn' %></li>
      <% end %>
    </ul>
    </div>
  </div>
</nav>
<div class="container">
  <% flash.each do |type, msg| %>
    <%= content_tag :div, msg, class: "flash_#{type}" %>
  <% end %>
  <%= yield %>
</div>

</body>
</html>

app/views/links/edit.html.erb
<%= form_for @link do |f| %>
  <%= f.label :url %>
  <%= f.text_field :url %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.submit %>
<% end %>

app/views/links/index.html.erb
<h1>Links</h1>
<%= form_for :link, url: links_path, html: {class: 'new_link'} do |f| %>
  <h5>Add Link</h5>
  <%= f.label :url %>
  <%= f.text_field :url %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.button 'Submit', class: 'btn-sm btn btn-default' %>
<% end %>
<input type='text' id='search' placeholder="Search">
<table class="table">
  <tr>
    <th>Link <small>(<a href="#" class='sortByTitle'>sort</a>)</small></th>
    <th>Edit</th>
    <th>Delete</th>
    <th>Read <small>(<a href="#" class='sortByStatus'>sort</a>)</small></th>
  </tr>
  <% @links.each do |link| %>
    <tr data-id='<%= link.id %>' data-title='<%= link.title %>' class='<%= link.read %> link'>
      <td><%= link_to link.title, link.url %></td>
      <td><%= link_to 'Edit', edit_link_path(link) %></td>
      <td><%= link_to 'Delete', link_path(link), method: 'delete' %></td>
      <% if link.read %>
        <td><%= link_to 'Mark as Unread', '#', id: 'read' %></td>
      <% else %>
        <td><%= link_to 'Mark as Read', '#', id: 'read' %></td>
      <% end %>
    </tr>
  <% end %>
</table>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
  <%= f.label :email, "Email Address" %>
  <%= f.text_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password, id: 'password' %>
  <%= f.label :password_match, "Confirm Password" %>
  <%= f.password_field :password_match, id: 'p_match' %>
  <%= f.submit 'Sign Up', disabled: true, id: 'sign-up', class: 'btn btn-default'%>
<% end %>